baseURL = 'https://monsieurcharriere.github.io'
languageCode = "en-ca"
title = "Page d'accueil de M. Charri√®re"
theme = "LucentLink-Hugo"
minVersion = "0.115.0"

[params]
  description     = "A clean, customizable, and responsive Linktree-style landing page built using HTML, Tailwind CSS, and Font Awesome."
  googleAnalytics = ""    # your GA ID, if any

[outputs]
  home = ["HTML"]